version: '3'
services:
        mongodb:
                image: 'mongo'
                container_name: 'play-on-eleven-mongo'
                restart: always
                environment:
                        - MONGO_INITDB_DATABASE=play-dev
                        - MONGO_INITDB_ROOT_USERNAME=valou5940
                        - MONGO_INITDB_ROOT_PASSWORD=5ekr3t@
                volumes:
                        - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
                        - ./mongo-volume:/data/db
                ports:
                        - '27017:27017' 
        api: 
                build: .
                volumes:
                        - ./config/config-dev.json:/config/config-dev.json
                ports:
                        - "8080:8080"
                links: 
                        - mongodb